#!/usr/bin/env ruby

# Ensure this is chmod 755, and add the following line to ~/.bashrc:
#   complete -C path/to/this/script -o default cap
#
# Based entirely on my complete_rake.  See that for its inspiration.

require 'fileutils'

exit 0 unless File.file? File.join(Dir.pwd, 'Capfile')
exit 0 unless /^cap\b/ =~ ENV["COMP_LINE"]

def cap_silent_tasks
  cache_dir = File.join File.expand_path('~'), '.captabs'
  FileUtils.mkdir_p cache_dir
  if File.exists?( dotcache = File.join(cache_dir, "#{Dir.pwd.gsub %r{/}, '_'}") )
    File.read(dotcache)
  else
    tasks = `cap --tasks --verbose`.split("\n")[1..-1].select { |line| line =~ /^cap/ }.map { |line| line.split[1] }
    File.open(dotcache, 'w') { |f| f.puts tasks }
    tasks
  end
end

after_match = $'
task_match = (after_match.empty? || after_match =~ /\s$/) ? nil : after_match.split.last
tasks = task_match ?
  cap_silent_tasks.select { |t| /^#{Regexp.escape task_match}/ =~ t } :
  cap_silent_tasks

# handle namespaces
if task_match =~ /^([-\w:]+:)/
  upto_last_colon = $1
  after_match = $'
  tasks = tasks.map { |t| (t =~ /^#{Regexp.escape upto_last_colon}([-\w:]+)$/) ? "#{$1}" : t }
end

puts tasks
exit 0
