#!/bin/sh
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=ruby
mv .git/tags.$$ .git/tags

