#!/bin/sh
#
# Hook that rejects files containing words in blacklist.

BLACKLIST="puts\|debugger\|binding.pry\|console"
 
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
 
for FILE in `git diff-tree --no-commit-id --name-only -r $against` ; do
    if grep -wq $BLACKLIST $FILE; then
      echo "$FILE contains one or more blacklisted words ($BLACKLIST)."
      echo "You can skip this check with --no-verify."
      exit 1
    fi
done
